# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_BREWERY', [dirname(__file__)])
        except ImportError:
            import _BREWERY
            return _BREWERY
        if fp is not None:
            try:
                _mod = imp.load_module('_BREWERY', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _BREWERY = swig_import_helper()
    del swig_import_helper
else:
    import _BREWERY
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def setup():
  return _BREWERY.setup()
setup = _BREWERY.setup

def loop():
  return _BREWERY.loop()
loop = _BREWERY.loop

def stopControls():
  return _BREWERY.stopControls()
stopControls = _BREWERY.stopControls

def get_Tm1_BREWING_1_wtime():
  return _BREWERY.get_Tm1_BREWING_1_wtime()
get_Tm1_BREWING_1_wtime = _BREWERY.get_Tm1_BREWING_1_wtime

def get_Tm1_BREWING_1_B_TempFil():
  return _BREWERY.get_Tm1_BREWING_1_B_TempFil()
get_Tm1_BREWING_1_B_TempFil = _BREWERY.get_Tm1_BREWING_1_B_TempFil

def get_Tm1_BREWING_1_B_TempSet():
  return _BREWERY.get_Tm1_BREWING_1_B_TempSet()
get_Tm1_BREWING_1_B_TempSet = _BREWERY.get_Tm1_BREWING_1_B_TempSet

def get_Tm1_BREWING_1_B_ElemModInd():
  return _BREWERY.get_Tm1_BREWING_1_B_ElemModInd()
get_Tm1_BREWING_1_B_ElemModInd = _BREWERY.get_Tm1_BREWING_1_B_ElemModInd

def get_Tm1_BREWING_1_M_TempFil():
  return _BREWERY.get_Tm1_BREWING_1_M_TempFil()
get_Tm1_BREWING_1_M_TempFil = _BREWERY.get_Tm1_BREWING_1_M_TempFil

def get_Tm1_BREWING_1_M_TempSet():
  return _BREWERY.get_Tm1_BREWING_1_M_TempSet()
get_Tm1_BREWING_1_M_TempSet = _BREWERY.get_Tm1_BREWING_1_M_TempSet

def get_Tm1_BREWING_1_requestpermission():
  return _BREWERY.get_Tm1_BREWING_1_requestpermission()
get_Tm1_BREWING_1_requestpermission = _BREWERY.get_Tm1_BREWING_1_requestpermission

def get_Tm1_BREWING_1_C_State():
  return _BREWERY.get_Tm1_BREWING_1_C_State()
get_Tm1_BREWING_1_C_State = _BREWERY.get_Tm1_BREWING_1_C_State

def get_Tm1_BREWING_1_timeleft():
  return _BREWERY.get_Tm1_BREWING_1_timeleft()
get_Tm1_BREWING_1_timeleft = _BREWERY.get_Tm1_BREWING_1_timeleft

def set_Tm1_BREWING_1_B_TempSet(*args):
  return _BREWERY.set_Tm1_BREWING_1_B_TempSet(*args)
set_Tm1_BREWING_1_B_TempSet = _BREWERY.set_Tm1_BREWING_1_B_TempSet

def set_Tm1_BREWING_1_M_TempSet(*args):
  return _BREWERY.set_Tm1_BREWING_1_M_TempSet(*args)
set_Tm1_BREWING_1_M_TempSet = _BREWERY.set_Tm1_BREWING_1_M_TempSet

def set_Tm1_BREWING_1_grantpermission(*args):
  return _BREWERY.set_Tm1_BREWING_1_grantpermission(*args)
set_Tm1_BREWING_1_grantpermission = _BREWERY.set_Tm1_BREWING_1_grantpermission

def set_Tm1_BREWING_1_C_State(*args):
  return _BREWERY.set_Tm1_BREWING_1_C_State(*args)
set_Tm1_BREWING_1_C_State = _BREWERY.set_Tm1_BREWING_1_C_State
# This file is compatible with both classic and new-style classes.


