# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 14:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AssetSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeriesDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('value', models.FloatField()),
                ('recipe_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.RecipeInstance')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.AssetSensor')),
            ],
        ),
        migrations.CreateModel(
            name='HeatedVessel',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brewery.Asset')),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.Brewery')),
            ],
            bases=('brewery.asset',),
        ),
        migrations.AddField(
            model_name='assetsensor',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.Asset'),
        ),
    ]
