# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0002_auto_20160409_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriesdatapoint',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
